omz_plugins:
  - zsh-autosuggestions
  - zsh-syntax-highlighting

omz_zshrc_settings: |
  export PATH=$PATH:/opt/homebrew/bin

  source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
  source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

  eval "$(starship init zsh)"
  eval "$(fnm env --use-on-cd)"
  eval "$(pyenv init -)"
  if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi

  source <(fzf --zsh)

  alias pn=pnpm
