omz_plugins:
  - zsh-autosuggestions
  - zsh-syntax-highlighting

omz_zshrc_settings: |
  export PATH=$PATH:/opt/homebrew/bin

  source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
  source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

  eval "$(starship init zsh)"
  eval "$(fnm env --use-on-cd)"

  source <(fzf --zsh)

  alias pn=pnpm
