#!/usr/bin/env sh

cd ~

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3 get-pip.py
sudo pip3 install --ignore-installed ansible
rm get-pip.py

# rm -rf dotfiles
# git clone https://github.com/UNRULYEON/dotfiles.git

rm -rf ansible
git clone https://github.com/UNRULYEON/ansible.git
cd ansible

ansible-galaxy install -r requirements.yml --force
ansible-playbook main.yml --ask-become-pass

cd ..
rm -rf ansible

echo "➜ Generate SSH keys: https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent"
echo "➜ Generate or import GPG keys: https://amar-kisoensingh.notion.site/GPG-Keys-ac46dff6e5b34733b9cf31e64f2f2274"
