---
- name: Sign commits by default
  ansible.builtin.shell:
    git config commit.gpgsign true

- name: Create remote branch by default when pushing
  ansible.builtin.shell:
    git config --global --add --bool push.autoSetupRemote true
