---
configure_dock: true
dockitems_remove:
  - 'App Store'
  - Calendar
  - Contacts
  - Downloads
  - FaceTime
  - Freeform
  - Keynote
  - Launchpad
  - Mail
  - Maps
  - Messages
  - Music
  - Notes
  - Numbers
  - Pages
  - Photos
  - Podcasts
  - Reminders
  - Safari
  - System Settings
  - TV
dockitems_persist:
  - name: 'Safari'
    path: '/Applications/Safari.app/'
    pos: 1
  - name: 'Google Chrome'
    path: '/Applications/Google Chrome.app/'
    pos: 2
  - name: 'Ghostty'
    path: '/Applications/Ghostty.app/'
    pos: 3
  - name: 'Visual Studio Code'
    path: '/Applications/Visual Studio Code.app/'
    pos: 4
  - name: 'Notion'
    path: '/Applications/Notion.app/'
    pos: 5
  - name: 'Music'
    path: '/Applications/Music.app/'
    pos: 6
