---
- name: Install packages to use a repository over HTTPS
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Add Docker's GPG key
  apt_key:
    url: '{{ docker_apt_gpg_key }}'
    state: present

- name: Add Docker repository
  apt_repository:
    repo: '{{ docker_apt_repository }}'
    state: present
    update_cache: true

- name: Install Docker
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: true
  ignore_errors: '{{ ansible_check_mode }}'

- include_tasks: docker-users.yml
  when: docker_users | length > 0
