---
- name: Create ~/.config folder
  ansible.builtin.file:
    path: ~/.config
    state: directory
    owner: amarkisoensingh
    group: staff

- name: Copy starship.toml
  template:
    src: starship.toml.j2
    dest: ~/.config/starship.toml
    owner: amarkisoensingh
    group: staff
    backup: true
    force: true
